### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by anegg0** [hevi1991/nextjs-upload-to-local-example#2]
Just a thank you note from a  dev who couldn't crack that one! You saved me from a horrible all-nighter.

**Comment by hevi1991** [comment]
> Just a thank you note from a dev who couldn't crack that one! You saved me from a horrible all-nighter.

I'm glad I could help you, Have a nice day :D

**Comment by vdwalia** [comment]
Yes yes, me to want to thank you so much for that.
