### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by notpritam** [hevi1991/nextjs-upload-to-local-example#3]
Can you please look into this , it is not working now , i have been trying to upload files to nextjs server which i am hosting on vercel , 
i tried this one also it is now working, 
can you please help me with this one...

**Comment by hevi1991** [comment]
Sorry, I haven't used Vercel before, but you can read the documentation at [https://vercel.com/docs/storage/vercel-blob/quickstart](https://vercel.com/docs/storage/vercel-blob/quickstart).

It can probably help you.

**Comment by hevi1991** [comment]
> Sorry, I haven't used Vercel before, but you can read the documentation at https://vercel.com/docs/storage/vercel-blob/quickstart.
> 
> It can probably help you.

I updated, it works now :D

https://nextjs-upload-to-local-example-khaki.vercel.app/

![image](https://github.com/hevi1991/nextjs-upload-to-local-example/assets/15024868/fa4a9632-a74a-44ff-a60b-3f7b083c8b31)
![r](https://github.com/hevi1991/nextjs-upload-to-local-example/assets/15024868/047d731c-427b-49ce-91ad-95450313ba01)
